server:
  port: 9000
  netty:
    connection-timeout: 2s
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    # cloud configuration server details
    config:
      uri: http://localhost:8888
      request-connect-timeout: 2000 # 2s
      request-read-timeout: 5000 # 5s
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1


    gateway:
      httpclient:
        connect-timeout: 5000 # 5s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s

      default-filters:
        - SaveSession
        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1
        # Attempt retry rules on some errors
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false

      # Main route definition
      routes:
        - id: service-a-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/service-a
          predicates:
            - Path=/service-a/**
        - id: service-b-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/service-b
          predicates:
            - Path=/service-b/**
        - id: service-c-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9003}/service-c
          predicates:
            - Path=/service-c/**

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: user
#    password: password
#    connection-timeout: 5s
  redis:
    connect-timeout: 2s
    host: ${REDIS_HOST:localhost}
    port: 6379
    timeout: 500ms
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: edge:gw
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: sb-service-edge
            client-secret: JQ164mayroloJH7l4dm4XhsDSSjsK2Zu
#            authorization-grant-type: authorization_code
#            redirect-uri: ${KEYCLOAK_URL:http://localhost:8080}/login/oauth2/code/keycloak
            scope: openid,roles
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/sbService
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowSize: 20
#        permittedNumberOfCallsInHalfOpenState: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 15000
#  timelimiter:
#    configs:
#      default:
#        timeoutDuration: 5s

info:
  system: Edge cloud gateway

management:
  endpoints:
    web:
      exposure:
        include: health, heapdump, info, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,redis
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.cloud.gateway: DEBUG
