global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'edge-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'edge-service:9000' ]
  - job_name: 'service-a'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-a:9001' ]
  - job_name: 'service-b'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-b:9002' ]
  - job_name: 'service-c'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service-c:9003' ]
#  - job_name: 'config-service'
#    scrape_interval: 2s
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'config-service:8888' ]
