version: "3.8"
services:

### Backing services
  sb-mysql:
    image: mysql:8
    container_name: sb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: mysqld --init-file /data/application/init.sql  --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: on-failure
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../sb-containers-data/sb-mysql:/var/lib/mysql
      - ./keycloak/init.sql:/data/application/init.sql
#  postgres:
#    image: postgres:14
#    container_name: "postgres"
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=dbadmin
#      - POSTGRES_PASSWORD=secret
#      - POSTGRES_DB=keycloak
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
  sb-redis:
    image: redis:7
    #    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    container_name: sb-redis
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ../sb-containers-data/sb-redis:/var/lib/redis
  sb-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: sb-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=secret
    volumes:
      - ../sb-containers-data/sb-rabbitmq:/var/lib/rabbitmq
  sb-keycloak:
    depends_on:
      - sb-mysql
    image: quay.io/keycloak/keycloak:18.0
    container_name: sb-keycloak
    command: "start-dev --db=mysql --db-url-host=sb-mysql --db-url=jdbc:mysql://sb-mysql/keycloak --db-username=keycloak --db-password=secret"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    ports:
      - 8080:8080
