server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 10s
    threads:
      max: 15
      min-spare: 5

spring:
  application:
    name: service-a
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/sbService
  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      username: ${CONFIGURATION_USER:configUser}
      password: ${CONFIGURATION_PASSWORD:configPassword}
      request-connect-timeout: 2000 # 2s
      request-read-timeout: 5000 # 5s
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

info:
  system: Service A

management:
  endpoints:
    web:
      exposure:
        include: flyway, health, heapdump, info, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    ROOT: INFO
    org.springframework.security: DEBUG
