apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
data:
  # echo -n "y344HccLyPPB3ehPu0HcF4e9vpNpXRgIfwB7MC8BpBNR2jUctXkOts8slxB7wPlH" | base64
  RABBITMQ_ERLANG_COOKIE: eTM0NEhjY0x5UFBCM2VoUHUwSGNGNGU5dnBOcFhSZ0lmd0I3TUM4QnBCTlIyalVjdFhrT3RzOHNseEI3d1BsSA==